CREATE DATABASE [PageBehaviourDb]
 CONTAINMENT = NONE
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PageBehaviourDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PageBehaviourDb]  SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET ANSI_NULLS OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET ANSI_PADDING OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET ARITHABORT OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET AUTO_CLOSE OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET AUTO_SHRINK OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [PageBehaviourDb]  SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [PageBehaviourDb]  SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET  DISABLE_BROKER
GO

ALTER DATABASE [PageBehaviourDb]  SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET TRUSTWORTHY OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [PageBehaviourDb]  SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET RECOVERY FULL
GO

ALTER DATABASE [PageBehaviourDb]  SET  MULTI_USER
GO

ALTER DATABASE [PageBehaviourDb]  SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [PageBehaviourDb]  SET DB_CHAINING OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [PageBehaviourDb]  SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [PageBehaviourDb]  SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [PageBehaviourDb]  SET QUERY_STORE = OFF
GO

ALTER DATABASE [PageBehaviourDb]  SET  READ_WRITE
GO
USE [PageBehaviourDb]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PageBehaviours](
	[BehaviourId] [uniqueidentifier] NOT NULL,
	[Browser] [varchar](500) NOT NULL,
	[Ip] [varchar](500) NOT NULL,
	[PageName] [varchar](500) NOT NULL,
	[PageParams] [varchar](max) NOT NULL,
 CONSTRAINT [PK_PageBehaviours] PRIMARY KEY CLUSTERED
(
	[BehaviourId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

